'use client';
import {Search,SlidersHorizontal} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {languages,Resource} from './types';
export type Filters={q:string;type:string;pricing:string;difficulty:string;language:string;duration:string;rating:string;sort:string};
export const initialFilters:Filters={q:'',type:'all',pricing:'all',difficulty:'all',language:'all',duration:'all',rating:'all',sort:'recommended'};
export function ResourceSearch({value,onChange}:{value:string;onChange:(v:string)=>void}){return <div className="resource-search"><Search size={18}/><Input aria-label="Search module resources" placeholder="Search within this module…" value={value} onChange={e=>onChange(e.target.value)}/></div>}
export function ResourceFilters({value:v,onChange}:{value:Filters;onChange:(v:Filters)=>void}){const update=(key:keyof Filters,value:string)=>onChange({...v,[key]:value});const select=(key:keyof Filters,label:string,options:[string,string][])=> <label><span>{label}</span><select aria-label={label} value={v[key]} onChange={e=>update(key,e.target.value)}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>;return <div className="resource-filters"><div className="resource-filter-top"><ResourceSearch value={v.q} onChange={s=>update('q',s)}/>{select('sort','Sort by',[['recommended','AI recommended'],['rating','Highest rated'],['popular','Most popular'],['shortest','Shortest'],['newest','Newest']])}</div><div className="resource-chips" aria-label="Resource type">{[['all','All'],['video','Videos'],['course','Courses'],['pdf','PDFs'],['documentation','Documentation'],['article','Articles'],['practice','Practice'],['project','Projects'],['github','GitHub'],['certification','Certifications']].map(([id,label])=><button key={id} aria-pressed={v.type===id} className={v.type===id?'active':''} onClick={()=>update('type',id)}>{label}</button>)}</div><div className="resource-filter-options"><SlidersHorizontal size={17}/>{select('pricing','Cost',[['all','Free & paid'],['free','Free'],['paid','Paid']])}{select('difficulty','Difficulty',[['all','Any level'],...['Beginner','Intermediate','Advanced'].map(s=>[s,s] as [string,string])])}{select('language','Language',[['all','All languages'],...Object.entries(languages)])}{select('duration','Duration',[['all','Any duration'],['30','Up to 30 minutes'],['60','Up to 1 hour'],['180','Up to 3 hours']])}{select('rating','Rating',[['all','Any rating'],['4','4 stars & up'],['4.5','4.5 stars & up']])}<button className="text-link" onClick={()=>onChange(initialFilters)}>Reset</button></div></div>}
export function filterResources(resources:Resource[],v:Filters){return resources.filter(r=>(v.type==='all'||r.resourceType===v.type)&&(v.pricing==='all'||r.pricingType===v.pricing)&&(v.difficulty==='all'||r.difficulty===v.difficulty)&&(v.language==='all'||r.language===v.language)&&(v.duration==='all'||r.duration!==null&&r.duration<=Number(v.duration))&&(v.rating==='all'||r.rating!==null&&r.rating>=Number(v.rating))&&`${r.title} ${r.description} ${r.provider}`.toLowerCase().includes(v.q.toLowerCase())).sort((a,b)=>v.sort==='rating'?(b.rating??-1)-(a.rating??-1):v.sort==='popular'?(b.reviewCount??-1)-(a.reviewCount??-1):v.sort==='shortest'?(a.duration??Infinity)-(b.duration??Infinity):v.sort==='newest'?(Date.parse(b.publishedAt||'')||0)-(Date.parse(a.publishedAt||'')||0):0)}
