'use client';
import {useEffect,useState} from 'react';
import {useTheme} from 'next-themes';
import {Languages,Sun,Moon,Monitor,Check,Search,LogOut} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {usePreferences} from './provider';
import {locales,Locale} from './locales';
export function LanguagePicker(){const {language,setLanguage,t,recent}=usePreferences(),[open,setOpen]=useState(false),[q,setQ]=useState('');const current=locales.find(l=>l.code===language)!;return <><button className="preference-control language-control" onClick={()=>setOpen(true)} aria-label={t('Language')}><Languages size={17}/><span>{current.name}</span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="language-dialog"><DialogHeader><DialogTitle>{t('Language')}</DialogTitle><DialogDescription>{t('Preferred learning language')}</DialogDescription></DialogHeader><div className="language-search"><Search size={16}/><Input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={t('Search languages')} aria-label={t('Search languages')}/></div>{recent.length>0&&!q&&<div className="recent-languages"><small>{t('Recently selected')}</small>{recent.map(code=>{const l=locales.find(l=>l.code===code);return l&&<button key={code} onClick={()=>{setLanguage(l.code);setOpen(false)}}>{l.name}</button>})}</div>}<div className="language-list">{locales.filter(l=>(l.name+' '+l.english).toLowerCase().includes(q.toLowerCase())).map(l=><button key={l.code} aria-pressed={language===l.code} onClick={()=>{setLanguage(l.code);setOpen(false);setQ('')}}><div><b lang={l.code}>{l.name}</b><small>{l.english}</small></div>{language===l.code&&<Check size={18}/>}</button>)}</div></DialogContent></Dialog></>}
export function ThemeSwitcher(){const {theme,setTheme}=useTheme(),{t}=usePreferences(),[ready,setReady]=useState(false);useEffect(()=>{setReady(true);const sync=(e:Event)=>setTheme((e as CustomEvent).detail);window.addEventListener('skillpath-theme-sync',sync);return()=>window.removeEventListener('skillpath-theme-sync',sync)},[setTheme]);return <div className="theme-switcher" role="group" aria-label={t('Theme')}>{[['light','Light',Sun],['dark','Dark',Moon],['system','System',Monitor]].map(([value,label,Icon]:any)=><button key={value} title={t(label)} aria-label={t(label)} aria-pressed={ready&&theme===value} className={ready&&theme===value?'active':''} onClick={()=>{setTheme(value);fetch('/api/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({theme:value})}).catch(()=>{})}}><Icon size={15}/></button>)}</div>}
export function PreferenceControls(){return <div className="preference-controls"><LanguagePicker/><ThemeSwitcher/></div>}
export function LogoutButton(){const {t}=usePreferences(),[busy,setBusy]=useState(false);return <button className="preference-control" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok)window.location.assign('/auth')}finally{setBusy(false)}}}><LogOut size={15}/><span>{t('Sign out')}</span></button>}
