export type Skill={name:string;level:number;source:string;evidence:string};
export const seedSkills:Skill[]=[{name:'Python',level:80,source:'assessment-verified',evidence:'Demo Python foundations assessment · 8/10'},{name:'SQL',level:65,source:'self-reported',evidence:'Demo data exploration project'},{name:'Machine Learning',level:60,source:'learning-derived',evidence:'Demo: completed supervised learning module'},{name:'Data Analysis',level:70,source:'self-reported',evidence:'Demo exploratory analysis portfolio'},{name:'Web Development',level:55,source:'self-reported',evidence:'Demo personal website'},{name:'Communication',level:75,source:'self-reported',evidence:'Demo presentation experience'},{name:'Java',level:40,source:'self-reported',evidence:'Demo introductory course'},{name:'Leadership',level:50,source:'self-reported',evidence:'Demo study-group coordination'}];
export const careers=[
{id:'ai-engineer',name:'AI Engineer',field:'AI & Data',color:'#a98aff',description:'Build intelligent systems that learn, reason, and solve meaningful problems.',requirements:{Python:80,'Machine Learning':75,'Deep Learning':65,Docker:50,'Cloud Deployment':50},interests:['Artificial intelligence','Problem solving'],why:{Python:'Implement data pipelines and model services.','Machine Learning':'Train and evaluate predictive models.','Deep Learning':'Build and tune neural networks.',Docker:'Package reproducible inference services.','Cloud Deployment':'Deploy and monitor production models.'}},
{id:'data-scientist',name:'Data Scientist',field:'AI & Data',color:'#51d8ce',description:'Turn complex data into experiments, insights, and better decisions.',requirements:{Python:75,SQL:70,'Data Analysis':80,'Machine Learning':70,Statistics:70},interests:['Research','Data'],why:{}},
{id:'data-analyst',name:'Data Analyst',field:'AI & Data',color:'#80a5ff',description:'Find the story in data and help teams make evidence-led decisions.',requirements:{SQL:80,'Data Analysis':80,Python:50,Communication:60},interests:['Data','Business'],why:{}},
{id:'software-developer',name:'Software Developer',field:'Engineering',color:'#e6a476',description:'Create reliable applications that make everyday life a little better.',requirements:{Python:60,'Web Development':75,Java:50,Communication:50},interests:['Building products','Problem solving'],why:{}},
{id:'ml-engineer',name:'Machine Learning Engineer',field:'AI & Data',color:'#d197ff',description:'Bridge machine learning research and reliable software systems.',requirements:{Python:85,'Machine Learning':80,Docker:65,'Cloud Deployment':65},interests:['Artificial intelligence','Engineering'],why:{}},
{id:'cloud-engineer',name:'Cloud Engineer',field:'Engineering',color:'#5cbbef',description:'Design resilient cloud infrastructure that helps ideas scale.',requirements:{Python:50,Docker:80,'Cloud Deployment':85,Linux:65},interests:['Infrastructure','Engineering'],why:{}},
{id:'backend-developer',name:'Backend Developer',field:'Engineering',color:'#af9ef9',description:'Build the APIs, services, and databases behind great products.',requirements:{Python:75,SQL:75,Docker:55,'Web Development':50},interests:['Building products','Engineering'],why:{}}
];
export function match(c:typeof careers[number],skills:Skill[]){const values=Object.entries(c.requirements);return Math.round(values.reduce((sum,[name,target])=>sum+Math.min((skills.find(s=>s.name===name)?.level||0)/(target||100),1),0)/values.length*100)}
export function pathFor(c:typeof careers[number]){return Object.keys(c.requirements).map((name,i)=>({id:c.id+'-'+i,name,description:`Develop practical ${name} skills through guided study and a small portfolio project.`,hours:8+i*2,url:name==='Python'?'https://docs.python.org/3/tutorial/':name==='SQL'?'https://www.postgresql.org/docs/current/tutorial.html':name==='Docker'?'https://docs.docker.com/get-started/':'https://developer.mozilla.org/en-US/docs/Learn_web_development'}))}
export const companies=[{id:'nimbus',name:'Nimbus Labs',city:'Chennai',type:'Startup',career:'AI Engineer',skills:['Python','Machine Learning','Docker'],role:'Junior AI Engineer',experience:'Entry level',lat:13.0827,lng:80.2707,color:'#8a83ee'},{id:'arc',name:'Arc Systems',city:'Chennai',type:'Enterprise',career:'Backend Developer',skills:['Python','SQL'],role:'Backend Developer',experience:'Entry level',lat:12.98,lng:80.22,color:'#47c6dd'},{id:'lumen',name:'Lumen Analytics',city:'Bengaluru',type:'Startup',career:'Data Analyst',skills:['SQL','Data Analysis'],role:'Data Analyst Intern',experience:'Internship',lat:12.97,lng:77.59,color:'#eca771'},{id:'orbit',name:'Orbit Cloud',city:'Chennai',type:'Enterprise',career:'Cloud Engineer',skills:['Docker','Cloud Deployment'],role:'Cloud Engineer',experience:'Experienced',lat:13.04,lng:80.24,color:'#70caaa'}];
export const assessmentQuestions=[{question:'Which Python type stores unique values?',options:['list','set','tuple'],correct:1},{question:'Which keyword defines a function?',options:['func','define','def'],correct:2},{question:'What does len([2, 4, 6]) return?',options:['3','6','12'],correct:0}];
