import {learningEvent,skillSnapshot} from '@/server/learning/events';
import {identity,sameOrigin,fail} from '@/server/middleware/auth';
import {database} from '@/server/services/db';
import {resolveModule} from '@/server/learning/catalog';
import {discover,rank} from '@/server/learning/discovery';
import {careers,match,Skill} from '@/src/services/catalog';
import {invokeAI} from '@/server/ai/provider';
import {z} from 'zod';
const preferences=z.object({language:z.enum(['en','ta','hi','te','ml','kn']).optional(),minutes:z.coerce.number().int().min(5).max(480).default(60),q:z.string().max(100).default('')});
export async function GET(req:Request,{params}:{params:Promise<{moduleId:string}>}){try{const u=await identity(),{moduleId}=await params,module=resolveModule(moduleId);if(!module)return Response.json({error:'Module not found'},{status:404});const db=database(),p=preferences.parse(Object.fromEntries(new URL(req.url).searchParams));const [profile,skill,states,activities,progress,result]=await Promise.all([db.prepare('SELECT preferred_language FROM profiles WHERE user_id=?').bind(u.userId).first<any>(),db.prepare('SELECT level FROM user_skills WHERE user_id=? AND name=?').bind(u.userId,module.name).first<any>(),db.prepare('SELECT * FROM resource_progress WHERE user_id=? AND module_id=?').bind(u.userId,moduleId).all<any>(),db.prepare('SELECT activity FROM module_activities WHERE user_id=? AND module_id=? AND completed=1').bind(u.userId,moduleId).all<any>(),db.prepare('SELECT progress FROM learning_progress WHERE user_id=? AND path_id=?').bind(u.userId,moduleId).first<any>(),db.prepare('SELECT score FROM assessment_results WHERE user_id=? AND assessment_id=? ORDER BY created_at DESC LIMIT 1').bind(u.userId,'hub-'+module.name).first<any>()]);const language=p.language||profile?.preferred_language||'en';const found=await discover({moduleId,topic:module.name,search:p.q,language});const resources=rank(found.resources,{level:skill?.level||0,language,minutes:p.minutes,completed:states.results.filter(s=>s.status==='completed').map(s=>s.resource_id),score:result?.score??null}).map(r=>{const state=states.results.find(s=>s.resource_id===r.id);return {...r,status:state?.status||'not-started',saved:!!state?.saved}});const {questions,resources:_,...info}=module;return Response.json({module:info,resources,mode:found.mode,language,proficiency:skill?.level??null,progress:progress?.progress||0,activities:activities.results.map(a=>a.activity),assessmentScore:result?.score??null,questions:questions.map(({correct,explanation,...q})=>q)})}catch(e){if(e instanceof z.ZodError)return Response.json({error:'Invalid discovery preferences'},{status:400});return fail(e)}}
export async function POST(req:Request,{params}:{params:Promise<{moduleId:string}>}){try{sameOrigin(req);const u=await identity(),{moduleId}=await params,module=resolveModule(moduleId);if(!module)return Response.json({error:'Module not found'},{status:404});const db=database(),body=z.object({action:z.enum(['resource','activity','assessment','complete','chat']),value:z.any()}).parse(await req.json()),now=new Date().toISOString();let statements:D1PreparedStatement[]=[];
if(body.action==='chat'){const message=z.string().trim().min(1).max(1000).parse(body.value);return Response.json(await invokeAI('chat',{message,moduleContext:{name:module.name,simple:module.simple,tamil:module.tamil,project:module.project,first:module.gains[0]}}))}
if(body.action==='resource'){const v=z.object({id:z.string().max(100),status:z.enum(['not-started','learning','completed']),saved:z.boolean()}).parse(body.value);const existing=await db.prepare('SELECT snapshot FROM resource_progress WHERE user_id=? AND module_id=? AND resource_id=?').bind(u.userId,moduleId,v.id).first<any>();const found=module.resources.find(r=>r.id===v.id)||(existing?JSON.parse(existing.snapshot):null)||(await discover({moduleId,topic:module.name,search:'',language:'en'})).resources.find(r=>r.id===v.id);if(!found)return Response.json({error:'Resource not found'},{status:404});statements.push(db.prepare('INSERT INTO resource_progress(user_id,module_id,resource_id,status,saved,snapshot,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,module_id,resource_id) DO UPDATE SET status=excluded.status,saved=excluded.saved,snapshot=excluded.snapshot,updated_at=excluded.updated_at').bind(u.userId,moduleId,v.id,v.status,v.saved?1:0,JSON.stringify(found),now))}
if(body.action==='activity'){const v=z.object({index:z.number().int().min(0).max(4),completed:z.boolean()}).parse(body.value);statements.push(db.prepare('INSERT INTO module_activities(user_id,module_id,activity,completed) VALUES(?,?,?,?) ON CONFLICT(user_id,module_id,activity) DO UPDATE SET completed=excluded.completed').bind(u.userId,moduleId,v.index,v.completed?1:0))}
if(body.action==='assessment'){const answers=z.array(z.number().int().min(0).max(2)).length(module.questions.length).parse(body.value),score=Math.round(answers.filter((a,i)=>a===module.questions[i].correct).length/answers.length*100);statements.push(db.prepare('INSERT OR IGNORE INTO assessments(id,skill,title) VALUES(?,?,?)').bind('hub-'+module.name,module.name,module.name+' introductory practice quiz'),db.prepare('INSERT INTO assessment_results(id,user_id,assessment_id,score,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,'hub-'+module.name,score,now),db.prepare('INSERT OR IGNORE INTO skills(name) VALUES(?)').bind(module.name),db.prepare("INSERT INTO user_skills(user_id,name,level,source,evidence) VALUES(?,?,?,'assessment-verified',?) ON CONFLICT(user_id,name) DO UPDATE SET level=excluded.level,source=excluded.source,evidence=excluded.evidence").bind(u.userId,module.name,score,`Introductory Skill Path practice quiz: ${score}% on ${now.slice(0,10)}. Not a professional certification.`));statements.push(learningEvent(u.userId,'assessment',module.name+' · '+score+'%'),skillSnapshot(u.userId,module.name,score,'practice assessment'));await db.batch(statements);const skills=await db.prepare('SELECT name,level,source,evidence FROM user_skills WHERE user_id=?').bind(u.userId).all<Skill>();await db.batch(careers.map(c=>db.prepare('INSERT INTO career_matches(user_id,career_id,score,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id,career_id) DO UPDATE SET score=excluded.score,updated_at=excluded.updated_at').bind(u.userId,c.id,match(c,skills.results),now)));return Response.json({ok:true,score,feedback:module.questions.map((q,i)=>({correct:answers[i]===q.correct,explanation:q.explanation}))})}
if(body.action==='complete'){const count=await db.prepare('SELECT COUNT(*) AS n FROM module_activities WHERE user_id=? AND module_id=? AND completed=1').bind(u.userId,moduleId).first<any>();const score=await db.prepare('SELECT score FROM assessment_results WHERE user_id=? AND assessment_id=? ORDER BY created_at DESC LIMIT 1').bind(u.userId,'hub-'+module.name).first<any>();if(count.n<5||!score||score.score<67)return Response.json({error:'Complete the five learning activities and pass the practice quiz (at least 2 of 3) first.'},{status:400});statements.push(db.prepare('INSERT INTO learning_progress(user_id,path_id,progress,updated_at) VALUES(?,?,100,?) ON CONFLICT(user_id,path_id) DO UPDATE SET progress=100,updated_at=excluded.updated_at').bind(u.userId,moduleId,now))}
statements.push(learningEvent(u.userId,body.action,module.name+(body.action==='resource'?' · '+body.value.status:'')));if(statements.length)await db.batch(statements);
if(body.action==='activity'){const count=await db.prepare('SELECT COUNT(*) AS n FROM module_activities WHERE user_id=? AND module_id=? AND completed=1').bind(u.userId,moduleId).first<any>();await db.prepare('INSERT INTO learning_progress(user_id,path_id,progress,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id,path_id) DO UPDATE SET progress=excluded.progress,updated_at=excluded.updated_at').bind(u.userId,moduleId,count.n*16,now).run()}
return Response.json({ok:true})}catch(e){if(e instanceof z.ZodError)return Response.json({error:'Check your learning activity details.'},{status:400});return fail(e)}}
