import {careers,pathFor} from '@/src/services/catalog';
import {env} from 'cloudflare:workers';
import {identity} from '@/server/middleware/auth';
import {database} from '@/server/services/db';
export async function officerAccess(){const u=await identity(),db=database(),config=env as unknown as Record<string,string>;
 const administrators=(config.ADMIN_USER_IDS||'').split(',').map(s=>s.trim()).filter(Boolean);
 if(u.isDemo){const org='org-'+u.userId,now=new Date().toISOString();await db.batch([db.prepare('INSERT OR IGNORE INTO organizations(id,name,created_at) VALUES(?,?,?)').bind(org,'Fictional Workforce Demo',now),db.prepare('INSERT OR IGNORE INTO officers(user_id,organization_id,active) VALUES(?,?,1)').bind(u.userId,org),db.prepare("INSERT OR IGNORE INTO officer_roles(user_id,role) VALUES(?,'officer')").bind(u.userId)])}
 if(!u.isDemo&&administrators.includes(u.userId)){const org='org-'+u.userId,now=new Date().toISOString();await db.batch([db.prepare('INSERT OR IGNORE INTO organizations(id,name,created_at) VALUES(?,?,?)').bind(org,'Skill Path Workforce',now),db.prepare('INSERT OR IGNORE INTO officers(user_id,organization_id,active) VALUES(?,?,1)').bind(u.userId,org),db.prepare("INSERT OR IGNORE INTO officer_roles(user_id,role) VALUES(?,'admin')").bind(u.userId)])}
 const member=await db.prepare('SELECT o.organization_id,g.name FROM officers o JOIN organizations g ON g.id=o.organization_id WHERE user_id=? AND active=1').bind(u.userId).first<any>();
 if(!member)throw new Error('Forbidden');const roles=await db.prepare('SELECT role FROM officer_roles WHERE user_id=?').bind(u.userId).all<{role:string}>();if(!roles.results.some(r=>r.role==='admin'||r.role==='officer'))throw new Error('Forbidden');return {...u,organizationId:member.organization_id,organizationName:member.name,isAdmin:roles.results.some(r=>r.role==='admin')};
}
export function notification(recipient:string,org:string|null,type:string,title:string,body:string,matchId:string|null=null){return database().prepare('INSERT INTO notifications(id,recipient_id,organization_id,type,title,body,match_id,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),recipient,org,type,title,body,matchId,new Date().toISOString())}
export function log(org:string,actor:string,action:string,matchId:string|null=null,from:string|null=null,to:string|null=null){return database().prepare('INSERT INTO activity_logs(id,organization_id,actor_id,match_id,action,from_stage,to_stage,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),org,actor,matchId,action,from,to,new Date().toISOString())}
export async function visibleCandidates(org:string){const db=database();const rows=await db.prepare(`SELECT p.user_id,p.name,CASE WHEN v.location_visible=1 THEN p.location ELSE 'Private' END AS location,p.preferred_language,p.education,p.interests,g.career_id,v.available,v.contact_allowed,v.visible_skills,v.experience,v.is_demo FROM profiles p JOIN profile_visibility_settings v ON p.user_id=v.user_id LEFT JOIN career_goals g ON p.user_id=g.user_id WHERE v.visible=1 AND v.available=1 AND (v.organization_id=? OR (v.organization_id IS NULL AND ? NOT LIKE 'org-demo:%'))`).bind(org,org).all<any>();
 return Promise.all(rows.results.map(async p=>{const allowed:string[]=JSON.parse(p.visible_skills);const all=await db.prepare('SELECT name,level,source,evidence FROM user_skills WHERE user_id=?').bind(p.user_id).all<any>();const reviews=await db.prepare('SELECT skill,level,evidence,kind,notes FROM skill_verifications WHERE user_id=?').bind(p.user_id).all<any>();const skills=all.results.filter(s=>allowed.includes(s.name)).map(s=>({...s,reviewed:reviews.results.some(r=>r.skill===s.name&&r.level===s.level&&r.evidence===s.evidence),reviews:reviews.results.filter(r=>r.skill===s.name&&r.level===s.level&&r.evidence===s.evidence)}));const results=await db.prepare("SELECT a.score,a.created_at,s.skill,s.title FROM assessment_results a JOIN assessments s ON s.id=a.assessment_id WHERE a.user_id=?").bind(p.user_id).all<any>();const learning=await db.prepare('SELECT progress,path_id FROM learning_progress WHERE user_id=?').bind(p.user_id).all<any>();return {...p,skills,assessments:results.results.filter(r=>allowed.includes(r.skill)),learning:learning.results.filter(l=>careers.flatMap(pathFor).some(m=>m.id===l.path_id&&allowed.includes(m.name))),visible_skills:undefined}}));
}
