'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Leaflet from 'leaflet';
export type GeoPoint={id:string;name:string;lat:number;lng:number;color?:string;count?:number};
export default function GeoMap({points,selected,onSelect,region=false,position}:{points:GeoPoint[];selected?:string;onSelect:(id:string)=>void;region?:boolean;position?:{lat:number;lng:number}|null}){
const container=useRef<HTMLDivElement>(null),map=useRef<Leaflet.Map|null>(null),layers=useRef<Leaflet.LayerGroup|null>(null),lib=useRef<typeof Leaflet|null>(null),callback=useRef(onSelect),lastSelection=useRef(selected);callback.current=onSelect;const [ready,setReady]=useState(false),[error,setError]=useState(false);
useEffect(()=>{let cancelled=false;import('leaflet').then(L=>{if(cancelled||!container.current)return;lib.current=L;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const m=L.map(container.current,{zoomControl:false,scrollWheelZoom:false,zoomAnimation:!reduced,fadeAnimation:!reduced}).setView(region?[11.4,78.4]:[13.04,80.23],region?7:11);map.current=m;L.control.zoom({position:'bottomleft'}).addTo(m);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',className:'skillpath-basemap',maxZoom:19}).on('tileerror',()=>setError(true)).on('tileload',()=>setError(false)).addTo(m);layers.current=L.layerGroup().addTo(m);const resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(container.current);(m as any)._cleanup=()=>resize.disconnect();setReady(true)});return()=>{cancelled=true;if(map.current){(map.current as any)._cleanup?.();map.current.remove();map.current=null}}},[region]);
useEffect(()=>{if(!ready||!map.current||!lib.current||!layers.current)return;const L=lib.current;layers.current.clearLayers();for(const p of points){const node=document.createElement('div');node.className=region?'region-marker':'geo-pin';node.style.setProperty('--pin',p.color||'#e77c95');node.innerHTML=region?`<strong>${p.count||0}</strong>`:'<span></span>';const marker=L.marker([p.lat,p.lng],{icon:L.divIcon({html:node,className:'custom-map-marker '+(p.id===selected?'chosen':''),iconSize:region?[60,60]:[30,42],iconAnchor:region?[30,30]:[15,40]}),title:p.name,keyboard:true}).addTo(layers.current);const label=document.createElement('span');label.textContent=p.name;marker.bindTooltip(label,{direction:'top',offset:[0,-28]});marker.on('click',()=>callback.current(p.id))}if(position)L.circleMarker([position.lat,position.lng],{radius:9,color:'#a0dfff',fillColor:'#428cff',fillOpacity:.9}).bindTooltip('Your location · not saved').addTo(layers.current)},[ready,points,selected,position,region]);
useEffect(()=>{if(lastSelection.current===selected)return;lastSelection.current=selected;const p=points.find(p=>p.id===selected);if(p&&map.current&&ready)map.current.flyTo([p.lat,p.lng],region?8:12,{duration:1.1,animate:!window.matchMedia('(prefers-reduced-motion: reduce)').matches})},[selected,ready,region]);
useEffect(()=>{if(ready&&map.current&&points.length){const coordinates=points.map(p=>[p.lat,p.lng] as [number,number]);map.current.fitBounds(coordinates,{padding:[45,45],paddingBottomRight:window.innerWidth>760&&!region?[320,60]:[45,45],maxZoom:12,animate:false})}},[ready,points.map(p=>p.id).join(','),region]);
return <div className="real-map"><div ref={container} className="leaflet-surface"/>{error&&<div className="tile-error">Map tiles are unavailable. Company details and list view still work.</div>}<div className="map-coordinate">{region?'TAMIL NADU · REGIONAL TALENT':'OPPORTUNITY NETWORK · DEMO'}<span>EXPLORE YOUR NEXT DESTINATION</span></div></div>
}
