import {env} from 'cloudflare:workers';
export type AIAction='chat'|'career'|'skill-gap'|'analyze-call'|'voice';
export async function invokeAI(action:AIAction,input:Record<string,unknown>){
 const config=env as unknown as Record<string,string>;
 if(config.AI_MODE==='remote'&&config.AI_BASE_URL){try{const url=new URL(`/api/ai/${action}`,config.AI_BASE_URL);if(url.protocol!=='https:')throw new Error('HTTPS required');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(config.AI_API_KEY?{Authorization:`Bearer ${config.AI_API_KEY}`}:{})},body:JSON.stringify(input),signal:AbortSignal.timeout(7000)});if(!response.ok)throw new Error('AI offline');const data=await response.json();return {mode:'remote',data}}catch{return {mode:'mock',offline:true,data:mock(action,input)}}}
 return {mode:'mock',offline:false,data:mock(action,input)};
}
function mock(action:AIAction,input:Record<string,unknown>){
 if(action==='career'&&input.goal)return {text:`You have completed ${input.completed||0} of ${input.total||0} modules toward ${input.goal}. Focus next on ${Array.isArray(input.gaps)?input.gaps.slice(0,2).join(' and '):'the next required skill'}. Learn ${input.nextModule||'your next module'}, build its mini project, and request an evidence review when ready. A practice score alone does not establish job readiness.`};
 if(action==='chat'&&input.moduleContext){const c=input.moduleContext as Record<string,string>,message=String(input.message||'').toLowerCase();let text=c.simple;if(/tamil|தமிழ்/.test(message))text=c.tamil+' Resource language can be changed to Tamil in the filters; if no curated result is available, none is invented.';else if(/project/.test(message))text=c.project;else if(/30|minutes|time/.test(message))text=`For a 30-minute session: spend 10 minutes reviewing ${c.first}, 15 minutes trying an example, then 5 minutes writing what you learned. Resource durations are shown only when known.`;else if(/free/.test(message))text='Select Free in the resource filters. The recommended path does not require a paid purchase.';else if(/basic|already/.test(message))text=`Try the ${c.name} practice quiz, then focus on the mini project: ${c.project}`;else if(/quiz/.test(message))text='Open Take module assessment below the learning sequence. It provides feedback and updates your passport with introductory practice evidence.';else if(/first/.test(message))text=`Begin with ${c.first}. ${c.simple}`;return {text,next_steps:['Choose a resource','Try the module project','Take the practice quiz']}}
 if(action==='analyze-call')return {summary:'Simulated career exploration session. You explored backend development, communication, and practical project learning. These are demo suggestions, not an evaluation of your voice.',interests:['Backend Development'],goals:['Build a portfolio project'],learning_interests:['APIs and databases'],career_questions:['How can I become a backend developer?'],suggestions:[{kind:'skill',value:'Communication',level:60},{kind:'interest',value:'Backend Development'},{kind:'language',value:input.language==='ta'?'ta':'en'}]};
 if(action==='voice')return {text:input.language==='ta'?'வணக்கம்! உங்கள் திறன்கள் மற்றும் எதிர்கால இலக்குகளைப் பற்றி பேசலாம்.':'Welcome to Skill Path. Let’s explore your skills and the future you want to build.'};
 return {text:'Start with your existing skills. Choose a career in your universe, review its requirements, and build a roadmap from your gaps. Your match is a transparent skill comparison, not a prediction of success.',next_steps:['Review your Skill Passport','Explore career requirements','Complete one portfolio project']};
}
