import {z} from 'zod';
import {database} from '@/server/services/db';
import {identity,sameOrigin,fail} from '@/server/middleware/auth';
import {notification,log} from '@/server/recruitment/access';
const word=z.string().min(1).max(200);
export async function GET(){try{const u=await identity(),db=database();await db.prepare('INSERT OR IGNORE INTO profile_visibility_settings(user_id) VALUES(?)').bind(u.userId).run();const [privacy,notes,matches,interviews]=await Promise.all([db.prepare('SELECT * FROM profile_visibility_settings WHERE user_id=?').bind(u.userId).first(),db.prepare('SELECT * FROM notifications WHERE recipient_id=? ORDER BY created_at DESC LIMIT 50').bind(u.userId).all(),db.prepare("SELECT m.*,o.title,o.organization_name,o.location,o.description,o.deadline,o.employment_type,o.education,o.work_mode,o.salary,o.vacancies,c.response FROM candidate_matches m JOIN opportunities o ON m.opportunity_id=o.id LEFT JOIN candidate_interests c ON c.match_id=m.id WHERE m.user_id=? AND m.stage!='matched'").bind(u.userId).all<any>(),db.prepare('SELECT i.* FROM interviews i JOIN candidate_matches m ON m.id=i.match_id WHERE m.user_id=?').bind(u.userId).all()]);return Response.json({privacy,notifications:notes.results,matches:await Promise.all(matches.results.map(async m=>({...m,skills:(await db.prepare('SELECT * FROM opportunity_skills WHERE opportunity_id=?').bind(m.opportunity_id).all()).results}))),interviews:interviews.results,contactShares:(await db.prepare('SELECT match_id,shared_at FROM contact_shares WHERE user_id=?').bind(u.userId).all()).results})}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const u=await identity(),db=database(),b=z.object({action:word,value:z.unknown()}).parse(await req.json()),now=new Date().toISOString();let q:D1PreparedStatement[]=[];
if(b.action==='privacy'){const v=z.object({available:z.boolean(),visible:z.boolean(),locationVisible:z.boolean(),contactAllowed:z.boolean(),skills:z.array(word).max(100),experience:z.string().max(100)}).parse(b.value);const actual=(await db.prepare('SELECT name FROM user_skills WHERE user_id=?').bind(u.userId).all<{name:string}>()).results.map(s=>s.name);if(v.skills.some(s=>!actual.includes(s)))return Response.json({error:'Only your own skills can be shared.'},{status:400});q.push(db.prepare('INSERT INTO profile_visibility_settings(user_id,available,visible,location_visible,contact_allowed,visible_skills,experience,organization_id) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET available=excluded.available,visible=excluded.visible,location_visible=excluded.location_visible,contact_allowed=excluded.contact_allowed,visible_skills=excluded.visible_skills,experience=excluded.experience,organization_id=excluded.organization_id').bind(u.userId,+v.available,+v.visible,+v.locationVisible,+v.contactAllowed,JSON.stringify(v.skills),v.experience,u.isDemo?'org-'+u.userId:null));if(v.available&&v.visible&&!u.isDemo){const members=await db.prepare("SELECT DISTINCT organization_id FROM officers WHERE active=1 AND organization_id NOT LIKE 'org-demo:%'").all<{organization_id:string}>();for(const org of members.results)q.push(notification('organization',org.organization_id,'available','A beneficiary is now available','A beneficiary opted into discovery. Refresh matching to review job-relevant skills.'))}}
else if(b.action==='share-contact'){const v=z.object({id:word,share:z.boolean()}).parse(b.value);const m=await db.prepare("SELECT m.* FROM candidate_matches m JOIN candidate_interests i ON i.match_id=m.id WHERE m.id=? AND m.user_id=? AND i.response='interested'").bind(v.id,u.userId).first<any>();if(!m)return Response.json({error:'Accept the opportunity before sharing contact details.'},{status:409});if(v.share)q.push(db.prepare('INSERT INTO contact_shares(match_id,user_id,email,shared_at) VALUES(?,?,?,?) ON CONFLICT(match_id) DO UPDATE SET email=excluded.email,shared_at=excluded.shared_at').bind(v.id,u.userId,u.email,now),notification('organization',m.organization_id,'contact_shared','Contact sharing approved','A beneficiary explicitly shared their account email for this opportunity.',v.id));else q.push(db.prepare('DELETE FROM contact_shares WHERE match_id=? AND user_id=?').bind(v.id,u.userId))}
else if(b.action==='response'){const v=z.object({id:word,response:z.enum(['interested','not-interested','application'])}).parse(b.value),m=await db.prepare('SELECT * FROM candidate_matches WHERE id=? AND user_id=?').bind(v.id,u.userId).first<any>();if(!m)return Response.json({error:'Opportunity not found'},{status:404});if(v.response==='application'){const consent=await db.prepare("SELECT response FROM candidate_interests WHERE match_id=? AND user_id=? AND response='interested'").bind(v.id,u.userId).first();if(!consent)return Response.json({error:'Express interest before submitting an application.'},{status:409});q.push(db.prepare('INSERT OR IGNORE INTO applications(id,match_id,user_id,created_at) VALUES(?,?,?,?)').bind(v.id,v.id,u.userId,now))}else q.push(db.prepare('INSERT INTO candidate_interests(match_id,user_id,response,updated_at) VALUES(?,?,?,?) ON CONFLICT(match_id) DO UPDATE SET response=excluded.response,updated_at=excluded.updated_at').bind(v.id,u.userId,v.response,now));if(v.response==='not-interested')q.push(db.prepare('DELETE FROM contact_shares WHERE match_id=? AND user_id=?').bind(v.id,u.userId),db.prepare("UPDATE candidate_matches SET stage='declined',updated_at=? WHERE id=? AND user_id=?").bind(now,v.id,u.userId));if(v.response!=='not-interested')q.push(db.prepare('UPDATE candidate_matches SET stage=?,updated_at=? WHERE id=? AND user_id=?').bind(v.response,now,v.id,u.userId));q.push(notification('organization',m.organization_id,v.response,'Beneficiary response',`A beneficiary responded: ${v.response}.`,v.id),log(m.organization_id,u.userId,'Beneficiary '+v.response,v.id,m.stage,v.response==='not-interested'?m.stage:v.response))}
else if(b.action==='interview-response'){const v=z.object({id:word,response:z.enum(['accepted','declined'])}).parse(b.value);const i=await db.prepare('SELECT i.*,m.organization_id FROM interviews i JOIN candidate_matches m ON m.id=i.match_id WHERE i.id=? AND m.user_id=?').bind(v.id,u.userId).first<any>();if(!i)return Response.json({error:'Interview not found'},{status:404});q.push(db.prepare('UPDATE interviews SET status=? WHERE id=?').bind(v.response,v.id),notification('organization',i.organization_id,'interview_response','Interview response','Beneficiary '+v.response+' the proposed interview.',i.match_id),log(i.organization_id,u.userId,'Interview '+v.response,i.match_id))}
else if(b.action==='read'){q.push(db.prepare('UPDATE notifications SET read_at=? WHERE recipient_id=?').bind(now,u.userId))}
else return Response.json({error:'Unknown action'},{status:400});await db.batch(q);return Response.json({ok:true})}catch(e){if(e instanceof z.ZodError)return Response.json({error:'Check your privacy settings.'},{status:400});return fail(e)}}
