import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {resolveModule} from './catalog';
import type {Resource} from '@/src/features/learning/types';
export type ResourceQuery={moduleId:string;topic:string;search:string;language:string};
export interface ResourceProvider {name:string;search(query:ResourceQuery):Promise<Resource[]>}
const remoteSchema=z.object({id:z.string().regex(/^[\w-]{1,100}$/),moduleId:z.string(),title:z.string().min(1).max(200),description:z.string().max(1000),provider:z.string().max(100),url:z.string().url(),resourceType:z.enum(['video','course','pdf','documentation','article','practice','project','github','certification']),pricingType:z.enum(['free','paid']),difficulty:z.enum(['Beginner','Intermediate','Advanced']),language:z.enum(['en','ta','hi','te','ml','kn']),price:z.string().max(100).nullable().default(null),rating:z.number().min(0).max(5).nullable().default(null),reviewCount:z.number().int().nonnegative().nullable().default(null),duration:z.number().positive().nullable().default(null),certificate:z.boolean().nullable().default(null),publishedAt:z.string().datetime().nullable().default(null),instructor:z.string().max(100).nullable().default(null)});
export const curatedProvider:ResourceProvider={name:'Curated catalog',async search(query){return resolveModule(query.moduleId)?.resources||[]}};
// A server-side gateway may aggregate YouTube, course, GitHub and OER APIs.
// Only the module and search preferences leave this app; never learner identity or profile.
export const gatewayProvider:ResourceProvider={name:'Resource gateway',async search(query){const config=env as unknown as Record<string,string>;if(!config.RESOURCE_SEARCH_URL)return [];const url=new URL(config.RESOURCE_SEARCH_URL);if(url.protocol!=='https:')throw new Error('Resource gateway requires HTTPS');const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(config.RESOURCE_SEARCH_KEY?{Authorization:`Bearer ${config.RESOURCE_SEARCH_KEY}`}:{})},body:JSON.stringify(query),signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('Discovery unavailable');const body=await response.text();if(body.length>200000)throw new Error('Response too large');return z.array(remoteSchema).max(60).parse(JSON.parse(body)).filter(r=>r.moduleId===query.moduleId).map(r=>({...r,thumbnail:null,verified:false,source:'Connected resource provider'}))}};
export function normalize(resources:Resource[]){const seen=new Set<string>();return resources.filter(r=>{try{const u=new URL(r.url);if(u.protocol!=='https:'||u.username||u.password)return false;u.hash='';for(const key of [...u.searchParams.keys()])if(key.startsWith('utm_'))u.searchParams.delete(key);const key=u.href.replace(/\/$/,'');if(seen.has(key))return false;seen.add(key);return true}catch{return false}})}
export async function discover(query:ResourceQuery){let external:Resource[]=[];let mode='Curated catalog';try{external=await gatewayProvider.search(query);if(external.length)mode='Connected discovery + curated catalog'}catch{mode='Curated catalog · discovery temporarily unavailable'}return {resources:normalize([...(await curatedProvider.search(query)),...external]),mode}}
export function rank(resources:Resource[],learner:{level:number;language:string;minutes:number;completed:string[];score:number|null}){const target=(learner.score!==null&&learner.score<67)||learner.level<45?'Beginner':learner.level<80?'Intermediate':'Advanced';return resources.map(r=>{const reasons:string[]=[];let score=10;if(r.language===learner.language){score+=20;reasons.push('Matches your preferred language')}if(r.difficulty===target){score+=18;reasons.push('Fits your current proficiency')}if(r.source==='Curated official resource'){score+=12;reasons.push('Selected educational source')}if(r.pricingType==='free')score+=5;if(r.duration&&r.duration<=learner.minutes){score+=10;reasons.push('Fits your available time')}if(learner.completed.includes(r.id))score-=60;else reasons.push('Not yet completed');if(r.rating!==null)score+=r.rating;return {...r,rank:score,reason:reasons.slice(0,3).join(' · ')}}).sort((a,b)=>b.rank-a.rank)}
